from enum import Enum

class VisualizationType(Enum):
  NODELINK = "NODELINK"
  MATRIX = "MATRIX"
  NODETRIX = "NODETRIX"
  NODELINK_MAP = "NODELINK_MAP"
  PAOHVIS = "PAOHVIS"
  CHORD_DIAGRAM = "CHORD_DIAGRAM"
  TREEMAP = "TREEMAP"

class NobreVisualizations(Enum):
  NODELINK = "NODELINK"
  NODELINK_FACETING = "NODELINK_FACETING"
  NODELINK_POSITIONING = "NODELINK_POSITIONING"
  MATRIX = "MATRIX"
  QUILTS = "QUILTS"
  BIOFABRIC = "BIOFABRIC"
  TREEMAP = "TREEMAP"
  SUNBURST = "SUNBURST"